### ISSUE TITLE
Modus Layout CSS changes (for dark mode)

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#136]
We need to add the following Modus layout changes for dark mode:

```scss
// Modus Layout
.modus-header {
  border-bottom: 1px solid #171c1e;
}

.modus-content {
  background-color: #171c1e;
}

.modus-body .modus-sidebar {
  background-color: #171c1e;
  border-right: 1px solid #171c1e;
}

.modus-panel {
  background-color: #252a2e;

  .panel-header,
  .panel-footer {
    background-color: #171c1e;
    border-color: #464b52;
  }

  .panel-body {
    background-color: #252a2e;
    .static-container {
      border-color: #464b52;
    }
  }
}
```
