### ISSUE TITLE
Cards Header and Footer is not correct gray in dark mode

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#140]
The card component doesn't have correct color border for header and footer.
See: https://modus-bootstrap.trimble.com/components/cards/#header-and-footer

We need to add the following CSS:

```css
.card-header:first-child {
  border-bottom-color: #464b52;

.card-footer:last-child {
  border-top-color: #464b52;
}
```
