### ISSUE TITLE
Duplicated btn-primary active state rules in SCSS

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#229]
### Describe the issue

The `_dark-theme.scss` has a duplicated ruleset. We should remove the first set which is incorrect.

```css
.btn-primary:not(:disabled):not(.disabled):active,
.btn-primary:not(:disabled):not(.disabled).display-active,
.show > .btn-primary.dropdown-toggle {
  background-color: #0189d2 !important;
  border-color: #0189d2 !important;
}
.btn-primary:not(:disabled):not(.disabled):active,
.btn-primary:not(:disabled):not(.disabled).display-active,
.show > .btn-primary.dropdown-toggle {
  background-color: #004f83 !important;
  border-color: #004f83 !important;
}
```

Thanks for spotting this @msankaran0712 !
