### ISSUE TITLE
Fix SonarQube Scan GH Action

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#263]
REF: https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/blob/main/.github/workflows/sonar-scan.yml

The scan isn't working properly. we need 

```yml
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

and add it ton run on demand with:
`  workflow_dispatch:`

and also specify it to run on Node v16 (Node v18 isn't supported yet)
