### ISSUE TITLE
Add a vertical rule helper class

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#90]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [x] I have read the [contributing guidelines](https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/blob/main/.github/CONTRIBUTING.md)

### Proposal

We sometimes need to use vertical rules in web apps and navbars. It'd be helpful to have a .vr vertical rule class in Modus Bootstrap. Bootstrap v5 has one so I propose that we port that over. The CSS for it is very small:

```css
.vr {
  display: inline-block;
  align-self: stretch;
  width: 1px;
  min-height: 1em;
  background-color: currentColor;
  opacity: 0.25;
}
```

### Motivation and context

I've used this on RouteReporter for some content in panels and the navbar to separate the Trimble logo and the app name. I'd like to use the same CSS/HTML on other webapps so I think it might make sense to add to Modus Bootstrap.

REF: https://github.com/twbs/bootstrap/blob/main/scss/helpers/_vr.scss
https://getbootstrap.com/docs/5.3/helpers/vertical-rule/
